services:
  susi:
    user: "${LOCAL_UID:-1000}:${LOCAL_GID:-1000}"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/opt/susi
    pre_start:
      - command: [ "sh", "-c", "npm install" ]
        user: "${LOCAL_UID:-1000}"
    ports:
      - "5002:5002"
    restart: unless-stopped
