from Susi_Variables.susi_variable import SusiInput, InputType, SusiVariableCategory


def get_io_settings():
    return [
        SusiInput(
            name="base_path",
            input_type=InputType.String,
            help="Base path for all relative paths in the config file. Defaults to current working directory.",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="csv_output_file",
            input_type=InputType.String,
            help="File path where the CSV output will be written.",
            optional=True,
            default_value="./output/out.csv",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="csv_time_unit",
            input_type=InputType.Dropdown,
            help="Time unit for CSV timestamp.",
            options=["seconds", "minutes", "hours", "date"],
            optional=False,
            default_value="date",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="csv_output_keys",
            input_type=InputType.Dropdown_With_Custom_Option,
            help="Specification for CSV output (String or Dict).",
            optional=False,
            options=["nothing", "all_incl_flows", "all_excl_flows", "Custom"],
            default_value=None,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="csv_output_weather",
            input_type=InputType.Boolean,
            help="If true, the weather data read in from a given weather file is exported to the CSV file.",
            optional=True,
            default_value=False,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="write_csv_continuously",
            input_type=InputType.Boolean,
            help="If true, CSV output will be written continuously, meaning in every time step. Activating this function will ensure partial output if the simulation fails during execution, however it also incurs a substantial performance penalty due to frequent file access.",
            optional=True,
            default_value=False,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="auxiliary_info",
            input_type=InputType.Boolean,
            help="If true, writes additional run information to markdown file.",
            optional=False,
            default_value=False,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="auxiliary_info_file",
            input_type=InputType.String,
            help="File path where auxiliary information will be written.",
            optional=True,
            default_value="./output/auxiliary_info.md",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="auxiliary_plots",
            input_type=InputType.Boolean,
            help="If true, ReSiE will create additional plots of components, if available (currently only available for geothermal probe).",
            optional=False,
            default_value=False,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="auxiliary_plots_path",
            input_type=InputType.String,
            help="Directory where auxiliary plots will be saved.",
            optional=True,
            default_value="./output/",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="auxiliary_plots_formats",
            input_type=InputType.Multiselect,
            help="File formats for auxiliary plots.",
            options=["html", "pdf", "png", "ps", "svg"],
            optional=False,
            default_value=["png"],
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="sankey_plot_file",
            input_type=InputType.String,
            help="File path where Sankey plot will be written.",
            optional=True,
            default_value="./output/output_sankey.html",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="sankey_plot",
            input_type=InputType.Dropdown_With_Custom_Option,
            help="Specification for Sankey plot (String or Dict).",
            optional=False,
            options=["nothing", "default", "Custom"],
            default_value=None,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="output_plot_file",
            input_type=InputType.String,
            help="File path where output line plot will be written.",
            optional=True,
            default_value="./output/output_plot.html",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="output_plot_time_unit",
            input_type=InputType.Dropdown,
            help="Unit for x-axis of output plot.",
            options=["seconds", "minutes", "hours", "date"],
            optional=False,
            default_value="date",
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="output_plot",
            input_type=InputType.Dropdown_With_Custom_Option,
            help="Specification for interactive HTML output plot (String or Dict).",
            options=["all_incl_flows", "all_excl_flows", "nothing", "Custom"],
            optional=False,
            default_value=None,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="plot_weather_data",
            input_type=InputType.Boolean,
            help="If true, the weather data read in from a given weather file is plotted to the line plot.",
            optional=True,
            default_value=False,
            variable_type=SusiVariableCategory.IOSetting,
        ),
        SusiInput(
            name="step_info_interval",
            input_type=InputType.Float,
            help="Defines how often a progress report on the loop over the timesteps of the simulation is logged to the info channel. This is useful to get an estimation of how much longer the simulation requires (albeit that such estimation is always inaccurate). If no value is given, automatically sets a value such that 20 reports are printed over the course of the simulation. To deactivate these reports, set this to 0.",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.IOSetting,
        ),
    ]


def get_simulation_parameters():
    return [
        SusiInput(
            name="start",
            input_type=InputType.Date,
            help="Start time of the simulation as datetime format.",
            optional=False,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="start_output",
            input_type=InputType.Date,
            help="The start time as datetime format at which the simulation begins to output the simulation results. Has to be equal or later than start. Can be used to perform heat-up simulation ahead of the actual simulation. Note that during heat-up, no warnings are output. The energies in the sankey, output CSV and output plot are starting at the start_output time specified.",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="end",
            input_type=InputType.Date,
            help=" End time (inclusive) of the simulation as datetime format, will be rounded down to the nearest multiple of time_step.",
            optional=False,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="start_end_unit",
            input_type=InputType.Date,
            help="Datetime format specifier for start, start_output and end time.",
            optional=False,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="time_step",
            input_type=InputType.Int,
            help="Time step in given time_step_unit format.",
            optional=False,
            default_value=900,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="time_step_unit",
            input_type=InputType.Dropdown,
            help="Unit of time_step.",
            options=["seconds", "minutes", "hours"],
            optional=False,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="weather_file_path",
            input_type=InputType.String,
            help="File path to the project-wide weather file. Can either be an EnergyPlus Weather File (EPW, time step has to be one hour, without leap day or DST) or a .dat file from the DWD (see https://kunden.dwd.de/obt/, free registration is required). See the component parameters on how to link weather file data to a component.",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="weather_interpolation_type_general",
            input_type=InputType.Dropdown,
            help="Interpolation type for weather data from weather file, except for solar radiation data.",
            options=[
                "stepwise",
                "linear_classic",
                "linear_time_preserving",
                "linear_solar_radiation",
            ],
            optional=True,
            default_value="linear_classic",
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="weather_interpolation_type_solar",
            input_type=InputType.Dropdown,
            help="Interpolation method for solar radiation data from weather file.",
            options=[
                "stepwise",
                "linear_classic",
                "linear_time_preserving",
                "linear_solar_radiation",
            ],
            optional=True,
            default_value="linear_solar_radiation",
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="latitude",
            input_type=InputType.Float,
            help="The latitude of the location in WGS84. If given, it overwrites the coordinates read out of the weather file!",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="longitude",
            input_type=InputType.Float,
            help="The longitude of location in WGS84. If given, it overwrites the coordinates read out of the weather file!",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="time_zone",
            input_type=InputType.Float,
            help="The time zone used in the current simulation in relation to UTC. If given, it overwrites the coordinates read out of the weather file! DWD-dat files are assumed to be in GMT+1.",
            optional=True,
            default_value=None,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="epsilon",
            input_type=InputType.Float,
            help=" The absolute tolerance for all floating-point comparisons in the simulation. Two values whose difference falls below this threshold are treated as equal. Defaults to 1e-9.",
            optional=True,
            default_value=1e-9,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
        SusiInput(
            name="force_profiles_to_repeat",
            input_type=InputType.Boolean,
            help="If set to true, all utilized profiles are allowed to be repeated, even if denied or not specified in the profile header! Attention: This parameter disables the profile parameter in the profile header! Defaults to false.",
            optional=True,
            default_value=False,
            variable_type=SusiVariableCategory.SimulationParameter,
        ),
    ]
